name: avaveen
favicon: null
layout_spectrum: 0.99511
typography_spectrum: 0.1184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.40391817153431475
  rhythmicContrast: 0.25
purpose: []
