name: avaveen
favicon: null
layout_spectrum: 0.99511
typography_spectrum: 0.24794
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d726b'
    - '#fefefe'
    - '#001018'
    - '#ca1911'
    - '#f9df35'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
