analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.27796
  rhythmicContrast: 0.75
  saturation: 0.509046
cta: {}
layout_spectrum: 0.99511
name: avaveen
opengraph: {}
purpose: []
typography_spectrum: 0.193256
