name: avaveen
favicon: null
layout_spectrum: 0.7786094478797168
typography_spectrum: 0.06989569682627916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24534066556952894
  lightness: 0.3337423512712121
  saturation: 0.40391817153431475
  rhythmicContrast: 0.6865719021297991
purpose: []
