name: avaveen
favicon: null
layout_spectrum: 0.74853
typography_spectrum: 0.05382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d726b'
    - '#fefefe'
    - '#001018'
    - '#ca1911'
    - '#f9df35'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
