name: avaveen
favicon: null
layout_spectrum: 0.74853
typography_spectrum: 0.203947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2c6202'
    - '#eeb300'
    - '#cb0025'
    - '#00dbf9'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
