analytics: {}
color:
  brandColors:
    - '#ba1460'
    - '#ee8800'
    - '#d73d00'
    - '#c13f65'
    - '#cb607e'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0.494243
  saturation: 0.509046
cta: {}
layout_spectrum: 0.014802
name: avaveen
opengraph: {}
purpose: []
typography_spectrum: 0.203947
